networks:
 default:
   name: elastic
   external: false

volumes:
  grafana_storage: {}

services:
  grafana:
    image: grafana/grafana:12.2
    container_name: grafana
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.iagorlabs.tech
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    volumes:
      - 'grafana_storage:/var/lib/grafana'

  loki:
    image: grafana/loki:3.5
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml